# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 205f4b75f3370ea484ea10abafc7d29fc924160ee9351f2a6577bc70a05e2070424e98f5ee24834320d62faec40a4a580fdf87c023128df95f0add23cc45e3c2

test:
  secret_key_base: 0faa89cdc40909e0d2f9383fed48d09ff848a7dcac2156bd2c61a768a80efed4f63cb038c7831edbd3080e8a39bb2125f897f0817967c03203484a5d7ecc61a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
